on: workflow_dispatch

name: Build
jobs:
  build:
    name: "Build Better-UI"
    runs-on: windows-latest
    strategy:
      matrix:
       node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install and npm run build
        run: |
          npm ci
          npm run build.all

      - uses: suisei-cn/actions-download-file@v1
        id: zip
        name: Download 7-zip
        with:
          url: "https://www.7-zip.org/a/7za920.zip"
          target: dist/7-zip

      - name: Decompress 7-zip
        run: 7z x dist\7-zip\7za920.zip -odist\7-zip\

      - uses: suisei-cn/actions-download-file@v1
        id: locate-plugin
        name: Download locate plguin
        with:
          url: "https://nsis.sourceforge.io/mediawiki/images/a/af/Locate.zip"
          target: dist/plugins

      - name: Decompress Locate plugin
        run: 7z x dist\plugins\Locate.zip -odist\plugins\

      - name: Install NSIS
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop bucket add extras
          scoop install nsis

      - name: Print NSIS version
        run: makensis -VERSION

      - name: Print NSIS compile flags
        run: makensis -HDRINFO

      - name: Install Nsis plguins
        run: |
          copy dist\plugins\Plugin\locate.dll "C:\Program Files (x86)\NSIS\Plugins\x86-ansi\" /Y
          copy dist\plugins\Include\Locate.nsh "c:\Program Files (x86)\NSIS\Include\" /Y

      - name: Create installer
        uses: joncloud/makensis-action@v3.4
        with:
          script-file: "installer/install.nsi"

#      - name: Push Build to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "dist/rf2-better-ui/*,dist/scripts"
#          token: ${{ secrets.TOKEN }}
